name: Deploy keshop to vercel

on:
  push:
    branches:
      - dev
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [16.x]

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      run: npm i
      run: npm run build --if-present
      run: npm run test
      - name: deploy to vercel
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN}} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 